version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Instalando dependencias necesarias para las pruebas...
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Ejecutando pruebas unitarias de la API...
      - python -m pytest
      - echo Iniciando sesión en Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Construyendo la imagen Docker del proyecto...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Construcción exitosa. Subiendo imágenes a Amazon ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Actualizando el archivo de despliegue con la nueva imagen de contenedor...
      - sed -i "s|<IMAGE_URI>|$REPOSITORY_URI:$IMAGE_TAG|g" Dockerrun.aws.json
      - echo ¡Todo listo para el despliegue!

artifacts:
  files:
    - Dockerrun.aws.json
    - .ebextensions/**/*
